name: Test & Deploy

on:
    push:
        branches:
            - master
        tags:
            - '*'
    pull_request:
        branches:
            - master

jobs:
    test:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Audit
              run: npm audit

            - name: Install packages
              run: npm install

            - name: Test
              run: npm test && npm run build
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    deploy:

        needs: [test]
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: Update @next version
              if: startsWith(github.ref, 'refs/heads/')
              run: npm version prerelease --no-git-tag-version --preid "${{ GITHUB_RUN_ID }}"

            - name: Deploy @next version
              if: startsWith(github.ref, 'refs/heads/')
              uses: JS-DevTools/npm-publish@v1
              with:
                  tag: next
                  token: ${{ secrets.NPM_TOKEN }}

            - name: Deploy @latest version
              if: startsWith(github.ref, 'refs/tags/')
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
